import json
import requests
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from config import Config

# Enhanced Prompt for AI Validation
AI_VALIDATOR_PROMPT = """
You are a Senior Trading Validator. Your job is to validate a signal generated by a rule-based strategy engine.

STRATEGY MODE: {mode}
PROPOSED SIGNAL: {signal}

TECHNICAL DATA:
{data_json}

INSTRUCTIONS:
1. Review the technical signal against the provided news and market context.
2. Special focus on ETF DATA: If the data is STALE (older than 24h), evaluate if the current chart and news still support the institutional narrative from that date.
3. If the technical signal is "LONG" but news is extremely bearish, you may invalidate it.
4. Provide a confidence score between 0 and 1.
5. Provide a brief, professional reasoning.

RESPONSE FORMAT (JSON ONLY):
{{
  "valid": true/false,
  "confidence": 0.XX,
  "reasoning": "string"
}}
"""

class StrategyV2:
    def __init__(self):
        self.custom_keys = {}
        if Config.GEMINI_API_KEY:
            from google import genai
            self.gemini_client = genai.Client(api_key=Config.GEMINI_API_KEY)
            self.gemini_model_id = "gemini-3.1-flash-lite-preview"

    def _calculate_rsi(self, prices, period=14):
        if len(prices) < period + 1: return 50
        delta = pd.Series(prices).diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        return float(rsi.iloc[-1])

    def _calculate_ema(self, prices, period):
        if len(prices) < period: return prices[-1]
        return float(pd.Series(prices).ewm(span=period, adjust=False).mean().iloc[-1])

    def analyze(self, symbol, price, klines, news_content, market_intel, mode="MOMENTUM", risk_profile="SAFETY", custom_keys=None):
        self.custom_keys = custom_keys or {}
        
        # 1. PREPROCESSING DATA
        if not klines or len(klines) < 30:
            return {
                "decision": "HOLD", 
                "reasoning": "Insufficient chart data. Need at least 30 candles.",
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }
        
        closes = [float(k[4]) if isinstance(k, list) else float(k.get('c')) for k in klines]
        volumes = [float(k[5]) if isinstance(k, list) else float(k.get('v')) for k in klines]
        quote_vols = [float(k[6]) if isinstance(k, list) else float(k.get('q', 0)) for k in klines]
        
        current_rsi = self._calculate_rsi(closes)
        ema_fast = self._calculate_ema(closes, 9)
        ema_slow = self._calculate_ema(closes, 21)
        
        import math
        if math.isnan(current_rsi): current_rsi = 50.0
        avg_vol = sum(volumes[-20:]) / 20
        curr_vol = volumes[-1]
        curr_vol_usd = quote_vols[-1]

        # ETF Data
        etf_data = market_intel.get("etf") or {}
        etf_inflow = float(etf_data.get("net_inflow", 0))
        etf_date_str = etf_data.get("date", "N/A")

        print(f"\n--- STRATEGY V2 CALCULATION ({mode}) ---")
        print(f"RSI: {current_rsi:.2f}")
        print(f"EMA9: {ema_fast:.2f} | EMA21: {ema_slow:.2f}")
        print(f"VOL: {curr_vol:.0f} (Avg: {avg_vol:.0f})")
        print(f"ETF NET INFLOW: ${etf_inflow:,.2f} ({etf_date_str})")
        
        # 2. RULE-BASED STRATEGY ENGINE
        signal = "HOLD"
        tech_reason = ""

        if mode == "CONTRARIAN":
            if current_rsi > 75: 
                signal = "SHORT"
                tech_reason = f"RSI Overbought ({current_rsi:.1f})"
            elif current_rsi < 25: 
                signal = "LONG"
                tech_reason = f"RSI Oversold ({current_rsi:.1f})"
            else:
                tech_reason = f"RSI Neutral ({current_rsi:.1f})"

        elif mode == "MOMENTUM":
            if ema_fast > ema_slow and curr_vol > avg_vol:
                signal = "LONG"
                tech_reason = f"EMA Cross Up + High Vol"
            elif ema_fast < ema_slow and curr_vol > avg_vol:
                signal = "SHORT"
                tech_reason = f"EMA Cross Down + High Vol"
            else:
                tech_reason = "No momentum trend detected"

        elif mode == "SMART_MONEY":
            is_stale = True
            try:
                etf_dt = datetime.strptime(etf_date_str, "%Y-%m-%d")
                if (datetime.now() - etf_dt) < timedelta(hours=24):
                    is_stale = False
            except: pass

            if etf_inflow > 50000000:
                if not is_stale or (ema_fast > ema_slow and current_rsi < 70):
                    signal = "LONG"
                    age = "RECENT" if not is_stale else f"STALE ({etf_date_str}) + CONFIRMED"
                    tech_reason = f"Strong ETF Inflow (${etf_inflow/1e6:.1f}M) - {age}"
                else:
                    tech_reason = f"Inflow is STALE ({etf_date_str}) & market is risky."
            elif etf_inflow < -50000000:
                if not is_stale or (ema_fast < ema_slow and current_rsi > 30):
                    signal = "SHORT"
                    age = "RECENT" if not is_stale else f"STALE ({etf_date_str}) + CONFIRMED"
                    tech_reason = f"Strong ETF Outflow (${etf_inflow/1e6:.1f}M) - {age}"
                else:
                    tech_reason = f"Outflow is STALE ({etf_date_str}) & market is risky."
            else:
                tech_reason = "Institutional flow is neutral"

        # Prepare strings for frontend
        tech_detail = f"RSI: {current_rsi:.1f} | EMA9: {ema_fast:.2f} | EMA21: {ema_slow:.2f} | Vol: ${curr_vol_usd:,.0f}. {tech_reason}"
        fund_detail = f"ETF Inflow: ${etf_inflow/1e6:.1f}M ({etf_date_str})."

        # 3. AI VALIDATOR LAYER
        if signal == "HOLD":
            print(f"RULE-BASED SIGNAL: HOLD ({tech_reason})")
            return {
                "decision": "HOLD",
                "reasoning": tech_reason,
                "technical_analysis": tech_detail,
                "fundamental_analysis": fund_detail,
                "confidence": 1.0,
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }

        print(f"RULE-BASED SIGNAL: {signal} ({tech_reason})")
        validation_data = {
            "rsi": round(current_rsi, 2),
            "ema_fast": round(ema_fast, 2),
            "ema_slow": round(ema_slow, 2),
            "etf_flow": f"${etf_inflow:,.2f}",
            "etf_data_date": etf_date_str,
            "data_status": "STALE" if (mode == "SMART_MONEY" and etf_date_str != "N/A" and is_stale) else "RECENT",
            "news_context": news_content[:1000]
        }
        
        system_msg = AI_VALIDATOR_PROMPT.format(
            mode=mode, signal=signal, data_json=json.dumps(validation_data)
        )
        ai_validation = self._call_ai_validator(system_msg, "Validate this signal.")
        
        if not ai_validation or not ai_validation.get("valid"):
            return {
                "decision": "HOLD",
                "reasoning": f"Strategy suggested {signal}, but AI rejected: {ai_validation.get('reasoning')}",
                "technical_analysis": tech_detail,
                "fundamental_analysis": ai_validation.get("reasoning", fund_detail),
                "confidence": ai_validation.get("confidence", 0),
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }

        # FINAL RISK MGMT
        p_float = float(price)
        return {
            "decision": signal,
            "reasoning": ai_validation.get("reasoning"),
            "technical_analysis": tech_detail,
            "fundamental_analysis": fund_detail,
            "confidence": ai_validation.get("confidence"),
            "params": {
                "leverage": 10 if risk_profile != "SAFETY" else 5,
                "margin_percent": 10,
                "tp_price": str(p_float * 1.03) if signal == "LONG" else str(p_float * 0.97),
                "sl_price": str(p_float * 0.985) if signal == "LONG" else str(p_float * 1.015)
            }
        }

    def _call_ai_validator(self, system_msg, user_msg):
        gemini_key = self.custom_keys.get("gemini_api_key") or Config.GEMINI_API_KEY
        if not gemini_key: return {"valid": True, "confidence": 0.5, "reasoning": "No AI key"}
        try:
            from google import genai
            client = genai.Client(api_key=gemini_key)
            resp = client.models.generate_content(
                model=self.gemini_model_id,
                contents=f"{system_msg}\n\n{user_msg}",
                config={"temperature": 0.1, "response_mime_type": "application/json"}
            )
            return json.loads(resp.text)
        except Exception as e:
            return {"valid": True, "confidence": 0.5, "reasoning": f"AI error: {e}"}
