import json
import requests
import pandas as pd
import numpy as np
from config import Config
from agents.prompts import (
    GEMINI_FILTER_PROMPT,
    MINIMAX_DECISION_PROMPT
)

# New Prompt for AI Validation
AI_VALIDATOR_PROMPT = """
You are a Senior Trading Validator. Your job is to validate a signal generated by a rule-based strategy engine.

STRATEGY MODE: {mode}
PROPOSED SIGNAL: {signal}

TECHNICAL DATA:
{data_json}

INSTRUCTIONS:
1. Review the technical signal against the provided news and market context.
2. If the technical signal is "LONG" but news is extremely bearish, you may invalidate it.
3. Provide a confidence score between 0 and 1.
4. Provide a brief, professional reasoning.

RESPONSE FORMAT (JSON ONLY):
{{
  "valid": true/false,
  "confidence": 0.XX,
  "reasoning": "string"
}}
"""

class StrategyV2:
    def __init__(self):
        self.custom_keys = {}
        if Config.GEMINI_API_KEY:
            from google import genai
            self.gemini_client = genai.Client(api_key=Config.GEMINI_API_KEY)
            self.gemini_model_id = "gemini-3.1-flash-lite-preview"

    def _calculate_rsi(self, prices, period=14):
        if len(prices) < period + 1: return 50
        delta = pd.Series(prices).diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        return float(rsi.iloc[-1])

    def _calculate_ema(self, prices, period):
        if len(prices) < period: return prices[-1]
        return float(pd.Series(prices).ewm(span=period, adjust=False).mean().iloc[-1])

    def analyze(self, symbol, price, klines, news_content, market_intel, mode="MOMENTUM", risk_profile="SAFETY", custom_keys=None):
        self.custom_keys = custom_keys or {}
        
        # 1. PREPROCESSING DATA
        if not klines or len(klines) < 30:
            return {
                "decision": "HOLD", 
                "reasoning": "Insufficient chart data for V2 Strategy. Need at least 30 candles.",
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }
        
        closes = [float(k[4]) if isinstance(k, list) else float(k.get('c')) for k in klines]
        volumes = [float(k[5]) if isinstance(k, list) else float(k.get('v')) for k in klines]
        
        # Check for stagnation (Zero movement)
        if len(set(closes)) <= 1 or sum(volumes) == 0:
            return {
                "decision": "HOLD",
                "reasoning": "Asset is stagnated or has zero volume. No trading possible.",
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }

        current_rsi = self._calculate_rsi(closes)
        ema_fast = self._calculate_ema(closes, 9)
        ema_slow = self._calculate_ema(closes, 21)
        
        # NaN Protection
        import math
        if math.isnan(current_rsi): current_rsi = 50.0
        if math.isnan(ema_fast): ema_fast = closes[-1]
        if math.isnan(ema_slow): ema_slow = closes[-1]
        avg_vol = sum(volumes[-20:]) / 20
        curr_vol = volumes[-1]

        print(f"\n--- STRATEGY V2 CALCULATION ({mode}) ---")
        print(f"RSI: {current_rsi:.2f}")
        print(f"EMA9: {ema_fast:.2f} | EMA21: {ema_slow:.2f}")
        print(f"VOL: {curr_vol:.0f} (Avg: {avg_vol:.0f})")

        # ETF Data
        etf_data = market_intel.get("etf") or {}
        etf_inflow = float(etf_data.get("net_inflow", 0))
        etf_date_str = etf_data.get("date", "N/A")
        print(f"ETF NET INFLOW: ${etf_inflow:,.2f} ({etf_date_str})")
        
        # 2. RULE-BASED STRATEGY ENGINE
        signal = "HOLD"
        tech_reason = ""

        if mode == "CONTRARIAN":
            # RSI > 75 and sentiment would be checked by AI
            if current_rsi > 75: 
                signal = "SHORT"
                tech_reason = f"RSI Overbought ({current_rsi:.1f})"
            elif current_rsi < 25: 
                signal = "LONG"
                tech_reason = f"RSI Oversold ({current_rsi:.1f})"
            else:
                signal = "HOLD"
                tech_reason = f"RSI Neutral ({current_rsi:.1f})"

        elif mode == "MOMENTUM":
            if ema_fast > ema_slow and curr_vol > avg_vol:
                signal = "LONG"
                tech_reason = f"EMA Cross Up with High Volume"
            elif ema_fast < ema_slow and curr_vol > avg_vol:
                signal = "SHORT"
                tech_reason = f"EMA Cross Down with High Volume"
            else:
                signal = "HOLD"
                tech_reason = "No momentum trend detected"

        elif mode == "SMART_MONEY":
            from datetime import datetime, timedelta
            
            is_stale = True
            try:
                etf_date = datetime.strptime(etf_date_str, "%Y-%m-%d")
                if datetime.now() - etf_date < timedelta(hours=48):
                    is_stale = False
            except: pass

            print(f"ETF DATA DATE: {etf_date_str} ({'STALE' if is_stale else 'RECENT'})")

            # Strategy: If stale, require technical confirmation (EMA)
            if etf_inflow > 50000000:
                if not is_stale or (ema_fast > ema_slow):
                    signal = "LONG"
                    tech_reason = f"Strong ETF Inflow (${etf_inflow/1e6:.1f}M) " + ("confirmed by EMA" if is_stale else "")
                else:
                    signal = "HOLD"
                    tech_reason = f"Strong ETF Inflow is STALE (${etf_date_str}) and price lacks momentum."
            elif etf_inflow < -50000000:
                if not is_stale or (ema_fast < ema_slow):
                    signal = "SHORT"
                    tech_reason = f"Strong ETF Outflow (${etf_inflow/1e6:.1f}M) " + ("confirmed by EMA" if is_stale else "")
                else:
                    signal = "HOLD"
                    tech_reason = f"Strong ETF Outflow is STALE (${etf_date_str}) and price is not dropping."
            else:
                signal = "HOLD"
                tech_reason = "Institutional flow is neutral"

        # 3. AI VALIDATOR LAYER
        print(f"RULE-BASED SIGNAL: {signal} ({tech_reason})")

        # Prepare detailed descriptions
        # Use Quote Volume (USD) for more intuitive display if available
        quote_volumes = [float(k[6]) if isinstance(k, list) else float(k.get('q', 0)) for k in klines]
        curr_vol_usd = quote_volumes[-1]
        
        tech_detail = f"RSI: {current_rsi:.1f} | EMA9: {ema_fast:.2f} | EMA21: {ema_slow:.2f} | Vol: ${curr_vol_usd:,.0f} ({curr_vol/avg_vol:.2f}x avg). {tech_reason}"
        fund_detail = f"ETF Inflow: ${etf_inflow/1e6:.1f}M ({etf_date_str})."
        
        if signal == "HOLD":
            print("Action: HOLD (No AI Validation required)")
            return {
                "decision": "HOLD",
                "reasoning": tech_reason,
                "technical_analysis": tech_detail,
                "fundamental_analysis": fund_detail,
                "confidence": 1.0,
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }

        # Call AI to validate
        validation_data = {
            "rsi": round(current_rsi, 2),
            "ema_fast": round(ema_fast, 2),
            "ema_slow": round(ema_slow, 2),
            "etf_flow": f"${etf_inflow:,.2f}",
            "news_context": news_content[:1000]
        }
        
        system_msg = AI_VALIDATOR_PROMPT.format(
            mode=mode, signal=signal, data_json=json.dumps(validation_data)
        )
        user_msg = "Validate this signal and return JSON."

        print(f"--- STAGE 2: AI VALIDATION (Gemini) for {signal} ---")
        ai_validation = self._call_ai_validator(system_msg, user_msg)
        
        if not ai_validation or not ai_validation.get("valid"):
            return {
                "decision": "HOLD",
                "reasoning": f"Strategy suggested {signal}, but AI invalidated it: {ai_validation.get('reasoning', 'No reason provided')}",
                "technical_analysis": tech_detail,
                "fundamental_analysis": ai_validation.get("reasoning", fund_detail),
                "confidence": ai_validation.get("confidence", 0),
                "params": {"leverage": 1, "margin_percent": 0, "tp_price": "0", "sl_price": "0"}
            }

        # 4. FINAL DECISION & RISK MGMT
        p_float = float(price)
        tp_pct = 0.03 # Default 3%
        sl_pct = 0.015 # Default 1.5%
        
        return {
            "decision": signal,
            "reasoning": ai_validation.get("reasoning"),
            "technical_analysis": tech_detail,
            "fundamental_analysis": fund_detail,
            "confidence": ai_validation.get("confidence"),
            "params": {
                "leverage": 10 if risk_profile != "SAFETY" else 5,
                "margin_percent": 10,
                "tp_price": str(p_float * (1 + tp_pct)) if signal == "LONG" else str(p_float * (1 - tp_pct)),
                "sl_price": str(p_float * (1 - sl_pct)) if signal == "LONG" else str(p_float * (1 + sl_pct))
            }
        }

    def _call_ai_validator(self, system_msg, user_msg):
        gemini_key = self.custom_keys.get("gemini_api_key") or Config.GEMINI_API_KEY
        if not gemini_key: 
            print("AI VALIDATOR: No Gemini API Key found.")
            return None
        
        try:
            from google import genai
            client = genai.Client(api_key=gemini_key)
            resp = client.models.generate_content(
                model=self.gemini_model_id,
                contents=f"{system_msg}\n\n{user_msg}",
                config={"temperature": 0.1, "response_mime_type": "application/json"}
            )
            
            raw_text = resp.text
            print(f"DEBUG AI RESPONSE: {raw_text}")
            
            parsed = json.loads(raw_text)
            print(f"AI VALIDATION: {'PASSED' if parsed.get('valid') else 'REJECTED'} (Confidence: {parsed.get('confidence', 0)})")
            return parsed
        except Exception as e:
            print(f"AI VALIDATOR ERROR: {e}")
            return {"valid": True, "confidence": 0.5, "reasoning": "AI validator error, proceeding with technical signal."}
